### ISSUE TITLE
Computing time AutoEvaluator 

### ISSUE THREAD

**Issue by jessiffmm** [JdeRobot/dl-DetectionSuite#109]
Hi!!

I was talking to Jose and he told me that in the .csv file that is generated, the computation times should also be included. At the moment I don't need it because I've seen that on the screen if some times are shown.But I told you about it because he told me to tell you.

Regards!!

**Comment by jessiffmm** [comment]
Hi @vinay0410 
I modified dl-DetectionSuite so that the times that I had mentioned previously appear. 
How can I upload it to the dl-detectionsuite repository?

Regards!!

**Comment by vinay0410** [comment]
Hi @jessiffmm ,
Just push the changes to your local fork and then open a pull request for the same.
I will review and merge it.

**Comment by jessiffmm** [comment]
Hi @vinay0410 

I have done the fork and pull request. Please, Telling me if I have done it well.
