### ISSUE TITLE
Update Instructions to install DetectionSuite using Docker

### ISSUE THREAD

**Issue by vinay0410** [JdeRobot/dl-DetectionSuite#114]

**Comment by sleep-404** [comment]
Would the following cover the steps:
 1.) Install Docker
 2.) Start the Docker daemon
 3.) Pull the docker image from the hub
 4.) Run the instance (This part does not does not require any installation as such , I guess )
If the above things are good to go , then I'll be editing the readme , for a PR

**Comment by vinay0410** [comment]
Hi @sleep-404 ,
Yes, these steps will cover running Detectionsuite from Docker,
but write these steps, as commands instead, so that users can just copy paste and run DetectionSuite

**Comment by sleep-404** [comment]
Yeah sure !!

**Comment by sleep-404** [comment]
well I have updated the wiki, but, because mac build fails this is returning  "All checks have failed" error

**Comment by sleep-404** [comment]
Hello @vinay0410 , I'm having little trouble running the Dataevaluationapp
I'm following the instruction present [here](https://github.com/JdeRobot/dl-DetectionSuite/wiki/Beginner's-Tutorial-to-DetectionSuite-Part-1).
After downloading the dataset and the classnames(.txt) do I need to move them to
`/opt/datasets/` and `/opt/datasets/names` directories ?
then what about 
`weightsPath: /opt/datasets/weights` and `evaluationsPath: /opt/datasets/eval` ?

**Comment by vinay0410** [comment]
You can move them to any directory you like, or not move them at all but you would have to write your config file accordingly.

The config file I have written assumes that the data has been moved to /opt/datasets

**Comment by sleep-404** [comment]
@vinay0410 I have sent a mail , may I know you opinion please ?

**Comment by sleep-404** [comment]
I think we can close this issue now

**Comment by jmplaza** [comment]
Solved in #118
