### ISSUE TITLE
Test dl-DetectionSuite

### ISSUE THREAD

**Issue by vmartinezf** [JdeRobot/dl-DetectionSuite#12]
Hi,

I'm trying to try DeepLearningSuite, but I don't know if I'm doing it the right way. I am able to run DatasetEvaluationApp, but I get a warning that I don't know if it should come out:

------------------------------------------------------------------
------------------------------------------------------------------
datasetPath
       /sampleFiles/datasets/home
evaluationsPath
       /sampleFiles/evaluations
inferencesPath
       /sampleFiles/evaluations
namesPath
       /sampleFiles/cfg/SampleGenerator
netCfgPath
       /sampleFiles/cfg/darknet
weightsPath
       /sampleFiles/weights/yolo_2017_07
------------------------------------------------------------------
------------------------------------------------------------------
------------------------------------------------------------------
------------------------------------------------------------------
datasetPath
       /sampleFiles/datasets/home
evaluationsPath
       /sampleFiles/evaluations
inferencesPath
       /sampleFiles/evaluations
namesPath
       /sampleFiles/cfg/SampleGenerator
netCfgPath
       /sampleFiles/cfg/darknet
weightsPath
       /sampleFiles/weights/yolo_2017_07
------------------------------------------------------------------
------------------------------------------------------------------
WARNING: Logging before InitGoogleLogging() is written to STDERR
W0129 17:31:21.528326 14332 ListViewConfig.cpp:89] path: /sampleFiles/weights/yolo_2017_07 does not exist
W0129 17:31:21.528415 14332 ListViewConfig.cpp:89] path: /sampleFiles/cfg/darknet does not exist
W0129 17:31:21.528518 14332 ListViewConfig.cpp:89] path: /sampleFiles/cfg/SampleGenerator does not exist

The result is:

![evaluation](https://user-images.githubusercontent.com/14541154/35522002-8506a4c0-051b-11e8-9ae5-e9fa10fe2822.png)

My appConfig.txt is:

--datasetPath
/mnt/large/pentalo/deep/datasets

--evaluationsPath
/mnt/large/pentalo/deep/evaluations

--weightsPath
/mnt/large/pentalo/deep/weights

--netCfgPath
/mnt/large/pentalo/deep/cfg/darknet

--namesPath
/mnt/large/pentalo/deep/cfg/SampleGenerator

--inferencesPath
/mnt/large/pentalo/deep/evaluations

Also, I tried to run SampleGenerationApp and the result is:

WARNING: Logging before InitGoogleLogging() is written to STDERR
W0129 17:25:17.989045 13853 SampleGenerationApp.cpp:99] Key: outputPath is not defined in the configuration file
W0129 17:25:17.989125 13853 SampleGenerationApp.cpp:99] Key: reader is not defined in the configuration file
W0129 17:25:17.989130 13853 SampleGenerationApp.cpp:99] Key: detector is not defined in the configuration file

The configuration file is:

--outputPath
/URJC

--dataPath
/sampleFiles/images
--detector
#datasetReader
deepLearning
#pentalo-bg

--inferencerImplementation
yolo

--inferencerNames
/sampleFiles/cfg/SampleGenerator/person1class.names

--inferencerConfig
/sampleFiles/cfg/darknet/yolo-voc-07-2017.cfg

--inferencerWeights
/sampleFiles/weights/yolo_2017_07/yolo-voc-07-2017.weights

--reader
#spinello
recorder-rgbd

--readerNames
none

Thank you very much,
Regards
.

**Comment by chanfr** [comment]
Hi,

First of all try only the DatasetEvaluationApp you should execute the app passing the configuration as follows:


./DatasetEvaluationApp --configFile=yourAppConfig.txt


yourAppConfig.txt should contains:

--datasetPath
<path to the dataset>
--evaluationsPath
<path of the evaluations>

--weightsPath
<path of the weights>

--netCfgPath
<path of the network configs>

--namesPath
<path of of the names files>

--inferencesPath
<path to store the inferences>


All this paths has been included into the "sampleFiles.zip" you have to modify the config file with the related paths on your computer

**Comment by vmartinezf** [comment]
Hi,

Sorry, I was wrong to put the content of appConfig.txt. What I have put is:

--datasetPath
/sampleFiles/datasets/home

--evaluationsPath
/sampleFiles/evaluations

--weightsPath
/sampleFiles/weights/yolo_2017_07

--netCfgPath
/sampleFiles/cfg/darknet

--namesPath
/sampleFiles/cfg/SampleGenerator

--inferencesPath
/sampleFiles/evaluations

But the error I get is the same:

WARNING: Logging before InitGoogleLogging() is written to STDERR
W0202 07:47:55.188529  4347 ListViewConfig.cpp:89] path: /sampleFiles/weights/yolo_2017_07 does not exist
W0202 07:47:55.188604  4347 ListViewConfig.cpp:89] path: /sampleFiles/cfg/darknet does not exist
W0202 07:47:55.188691  4347 ListViewConfig.cpp:89] path: /sampleFiles/cfg/SampleGenerator does not exist

Thank you so much,
Regards.

**Comment by chanfr** [comment]
Hi,
It seems that you are not writing the entire path name inside the configuration files, you should include the absolute path name.


Regards,
Fran.

**Comment by vmartinezf** [comment]
Hi,
It works now. I tried to follow the steps of the video of http://jderobot.org/Frivas-phd, but I don't see any file in Input Dataset.

Thanks,
Regards.

**Comment by chanfr** [comment]
![capture](https://user-images.githubusercontent.com/5627921/35993229-ef0de5d8-0d0c-11e8-89e6-2bb11f7c9516.png)

You may be selecting the wrong dataset type, the one I shared has our "own" dataset structure.


This can be also an improvement to auto-detect the type of the input dataset. 


regards,

**Comment by vmartinezf** [comment]
Hi,

I run the DatasetEvaluation, but I don't any file in Input Dataset. My configuration file is:

--datasetPath
/home/vanejessi/DeepLearningSuite/DeepLearningSuite/DatasetEvaluationApp/sampleFiles/datasets/home

--evaluationsPath
/home/vanejessi/DeepLearningSuite/DeepLearningSuite/DatasetEvaluationApp/sampleFiles/evaluations

--weightsPath
/home/vanejessi/DeepLearningSuite/DeepLearningSuite/DatasetEvaluationApp/sampleFiles/weights/yolo_2017_07

--netCfgPath
/home/vanejessi/DeepLearningSuite/DeepLearningSuite/DatasetEvaluationApp/sampleFiles/cfg/darknet

--namesPath
/home/vanejessi/DeepLearningSuite/DeepLearningSuite/DatasetEvaluationApp/sampleFiles/cfg/SampleGenerator

--inferencesPath
/home/vanejessi/DeepLearningSuite/DeepLearningSuite/DatasetEvaluationApp/sampleFiles/evaluations


The result is:

![detectionsuiteevaluation](https://user-images.githubusercontent.com/14541154/36801936-a71a97ba-1cb3-11e8-9fc1-6020dd3c504a.png)

Thanks,
Regards!

**Comment by chanfr** [comment]
Hi,
The dataset path should be the main path of the datasets, so the parent path of the one you have defined on the cfg.

Regards,
Fran.
