### ISSUE TITLE
Unable to use camera as input 

### ISSUE THREAD

**Issue by sleep-404** [JdeRobot/dl-DetectionSuite#123]
![err1](https://user-images.githubusercontent.com/31350263/55007971-4c33cd80-5006-11e9-99ad-68dcc16fc045.png)
![err3](https://user-images.githubusercontent.com/31350263/55008214-b0569180-5006-11e9-92be-4e2393a5c6ae.png)

**Comment by vinay0410** [comment]
What error do you get, when you try to run it using camera

**Comment by sleep-404** [comment]
Nothing is happening

**Comment by vinay0410** [comment]
Have patience, and see [this](https://www.youtube.com/watch?v=AWVdt7djJBg) video on how to use, and read the tutorial carefully.
First error:
`datasets/cfg` not found, because you current directory doesn't contain such a file.
That's why no config is being loaded into the GUI.
Fix that first

**Comment by sleep-404** [comment]
Sorry Vinay , gave relative path instead of absolute path. And named cfg as config .
Got little excited , and overlooked them
Thank you for explaining me so patiently.
Will go back to room and re run it.

**Comment by sleep-404** [comment]
Everything is working superfine !!
