### ISSUE TITLE
problem at trying gui app at beginner's tutorial

### ISSUE THREAD

**Issue by teamleader6** [JdeRobot/dl-DetectionSuite#125]
navigate to DatasetEvaluationApp directory in the build directory. There you will find an executable but i didn't find any excutable just cmakefiles , cmake_install. cmake and makefile

**Comment by sleep-404** [comment]
you need to build the repository before you start using it.
hope [this](https://www.youtube.com/watch?v=8B1YEygEL74) helps :)
