### ISSUE TITLE
Add Sample Working images and link to working videos of DetectionSuite

### ISSUE THREAD

**Issue by vinay0410** [JdeRobot/dl-DetectionSuite#126]
Currently, readme doesn't contain any images of this tool in action. This would help to demonstrate the capabilities of this tool.

**Comment by sleep-404** [comment]
shall I add the videos by reducing their lengths which were taken earlier ?

**Comment by sleep-404** [comment]
[Install JDE/dl-DetectionSuite from source
](https://youtu.be/HYuFFTnEn5s)
[Running DataEvaluation app](https://youtu.be/KFrEPCOA0p4)
do they meet the required conditions for them to be included in the readme ?

**Comment by vinay0410** [comment]
Hi @sleep-404 ,
The videos look fine to me. I was wondering if you could add them in a playlist, and we could then add the link to that playlist in the readme.

Also, there are some minor errors, for instance It’s DatasetEvaluationApp, not DataEvaluationApp.

If changing that would require lots of effort, then let it be, otherwise if it’s easy then please go ahead and change that.

If you have any other ideas on how to put them in readme. Feel free to share them

**Comment by sleep-404** [comment]
Done creating the playlist and editing the name.
Will update the readme as soon as I finish my classes
