### ISSUE TITLE
Viewing Spinello dataset

### ISSUE THREAD

**Issue by vinay0410** [JdeRobot/dl-DetectionSuite#22]
I was trying to view spinello's depth images. And the output I am getting is something like this.

![image](https://user-images.githubusercontent.com/18044818/37866217-abd6a6f6-2fad-11e8-806a-62eb7d97cfa1.png)

And it doesn't match with the video.
So is there some problem in conversion from grayscale to color mapping of depth ?
Or this is the desired output ?

This is a sample conversion from grayscale
![image](https://user-images.githubusercontent.com/18044818/37865560-3b71fb26-2fa4-11e8-9676-a71ef982d409.png)

**Comment by chanfr** [comment]
We tried o use spinello dataset but never make it work... we tried the conversion described by the author but measured do not corresponds. We also write him, but never answered. So not much to say... I tried lot of combinations and get stuck.
