### ISSUE TITLE
TensorFlow inference is quite slow inside DetectionSuite compared to that on ObjetcDetector

### ISSUE THREAD

**Issue by jmplaza** [JdeRobot/dl-DetectionSuite#32]
It typically took 20secs, and after #27 near 4.5secs according to @naxvm . But the same network model in ObjectDetector (python code) takes only 125ms. Maybe we should revisit this and find the cause of this delay (the C++ to/from Python conversion?)

**Comment by vinay0410** [comment]
Hi @naxvm and @jmplaza ,
Could you please share the network, of which statistics have been mentioned, so that I can test the same and report it on my end.

**Comment by naxvm** [comment]
Hello @vinay0410 

The network file which I've used was the v2. SSD Mobilenet (here is the link)[http://jderobot.org/store/deeplearning-networks/TensorFlow/ssd_mobilenet_v2_coco_2018_03_29.pb]. I've used it on GPU (not so fast one, but it makes 125 ms on objectdetector), inferring frames from a video in DetectionSuite. Could you give it a check? Thanks!!

**Comment by naxvm** [comment]
@vinay0410 I'm doing a fast test of the inference app. As I can see on the TensorFlow output, a new tf.Session() is being called to process each frame. I suspect that this could be guilty for that huge timing, as the network's first prediction is much slower (in objectdetector I make a first dummy inference before starting the on-flight process). Could you check this, or guide about where is the Python-TF code you are using? Thanks!!

**Comment by naxvm** [comment]
As I mentioned, a single Session instance is created for each frame on the [inference file](https://github.com/JdeRobot/dl-DetectionSuite/blob/c48f2dc3bca17b25729fd9485376042c2b1b7939/DeepLearningSuite/DeepLearningSuiteLib/python_modules/tensorflow_detect.py#L22).

This session should be persistent across the evaluated frames (that's the main reason why I created the (DetectionNetwork class)[https://github.com/JdeRobot/dl-objectdetector/blob/master/Net/TensorFlow/network.py] on objectdetector.

If the C++ interface allows you to create objects, feel free to use the class. For what I've seen, it's ready to go here (simple functions renaming). I am pretty sure this is the main reason which is bottlenecking us...

**Comment by vinay0410** [comment]
Hi @naxvm and @jmplaza ,
I tested the same network on DetectionSuite which is SSD MobileNet v2 COCO, and the inference speed I am getting is 150ms on CPU.
I think that you are still using a previous version of DetectionSuite, please try updating it.
I have also made a video proving the same fact, using updated DetectionSuite.
[Link to Video<br>![Detection Suite Tensorflow Inferencer](https://img.youtube.com/vi/wMtN1vuqGbc/0.jpg)](https://www.youtube.com/watch?v=wMtN1vuqGbc)

**Comment by naxvm** [comment]
Hello Vinay,

Sorry, it was my fault. I was on an old commit (I thought I was updated). Both TensorFlow and Keras inferences are working properly, similar timings than on objectdetector.

Closing this, thanks!
