### ISSUE TITLE
Add Support for Caffe Framework

### ISSUE THREAD

**Issue by vinay0410** [JdeRobot/dl-DetectionSuite#44]
Hi @chanfr ,
Actually, I wanted to discuss something about Caffe support. So, let me start with TensorFlow and Keras support first.
TensorFlow doesn't require anythink apart from the ```frozen_inference_graph.pb``` and is sufficient for generating inferences, for any network architecture, like SSD, Faster R-CNN, etc.
Whereas, Keras requires a config file and the weights for it, though, in newer versions only HDF5 file is enough which contains both.
But, it does require implementation of Custom functions like ```AnchorBoxesGenerator``` and ```L2Normalization``` which architectures like Faster R-CNN and SSD do require. And these functions have to be passed in the ModelBuilder.

Now, coming to Caffe, in order to implement support for networks like Faster R-CNN and SSD,  people have made changes to the base repository, and reinstalled it support custom architectures like Faster R-CNN and SSD, because there is no support for them in the base repository, and these custom functions cannot be passed in the Model Builder.

So, we are left with 2 solutions to implementing Caffe support:
1. Fork the base repository's code and change it according to our needs, but this will increase a dependency and users would have to build Caffe again for caffe support.
2. OpenCV's dnn module has already implemented the same by writing all the custom layers required and custom fucntions in C++, and they have also written parsers for config file and ```.caffemodel``` weights file.
And since OpenCV is already a dependency, we can use there module to implement caffe support.

Also, OpenCV doesn't have Keras support, and their TensorFlow support is too lengthy, and requires to generate a separate config file for the same.
So, we have better TensorFlow and Keras support, but we can use their Caffe implementation.

**Comment by chanfr** [comment]
Sure,
caffe has more sparse support than keras or tensor flow. Having more configuration to use caffe will not a problem, the wort thing of this part is having support with more than one caffe version using the same executable. That will be horrible. 

If OpenCV includes the custom layers we need and we can their wrapper will be fantastic.

regards
