### ISSUE TITLE
Calculation of Metrics in Evaluation

### ISSUE THREAD

**Issue by vinay0410** [JdeRobot/dl-DetectionSuite#45]
Hi @chanfr ,
I was going through the code written in ```DetectionsEvaluator.cpp``` [here](https://github.com/JdeRobot/dl-DetectionSuite/blob/master/DeepLearningSuite/DeepLearningSuiteLib/FrameworkEvaluator/DetectionsEvaluator.cpp#L57).
And, what if multiple objects of the same class are present. For example 4 chair(s) are present in a single sample. Then for a single detected chair, it will iterate over all the ground truth regions and the first one will be matched, which might not be the same object of the chair.

So, doesn't it assumes by default that detections are in the same order as Ground Truth Values.

**Comment by chanfr** [comment]
Sure,
we decided to match all object in between detection and ground truth just if the IOU between them is greater than 0.5. 

We don't compute the best IOU between both data.

Any suggestion about how in improve this matching between GT and detection?
We should take a look on how the detection is being evaluated in challenges.

**Comment by vinay0410** [comment]
Implemented in #63 and #62
