### ISSUE TITLE
Shift all logs to glog

### ISSUE THREAD

**Issue by vinay0410** [JdeRobot/dl-DetectionSuite#95]
Some of the logging work is done using ```std::cout``` in C++ and using ```print``` in python. It would be better for debugging purposes if Logging could be done using glog only.

**Comment by sleep-404** [comment]
Can you point out where exactly should I look in the directory for these files and a few resources for Glog documentaion ?
And how good should I be with Glog , would basic knowledge be sufficient for this task ?

**Comment by vinay0410** [comment]
glog is a logging library. You lean more about it [here](https://codeyarns.com/2017/10/26/how-to-install-and-use-glog/) and [here](http://rpg.ifi.uzh.ch/docs/glog.html)

There is no particular directory, they are everywhere.
we generally use LOG(INFO) << "message", LOG(WARNING) << "message" and LOG(ERROR) << "message" to log important information. 

You just have to replace std::cout << "message" with LOG(suitable_type) << "message".

**Comment by sleep-404** [comment]
Hello  @vinay0410 , just updated the PR , which solves this issue and the documentation.
Eagerly waiting for your feedback :)  !
